"""empty message

Revision ID: 16084d338c5a
Revises: 6cddbb032be6
Create Date: 2023-02-27 12:42:40.786009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16084d338c5a'
down_revision = '6cddbb032be6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
